# nginx ca cert self signed 

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: cert-manager
type: Opaque
data:
  tls.crt:  # content of ca.crt (converted to base64)
  tls.key:  # content of ca.key (converted to base64)
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nginx-clusterissuer
spec:
  ca:
    secretName: nginx-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: nginx
spec:
  secretName: nginx-tls-secret
  issuerRef:
    name: nginx-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.self.home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
  labels:
    app: nginx-app
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: nginx-redirecttohttps@kubernetescrd
spec:
  rules:
  - host: "nginx.self.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc 
            port:
              number: 80 
  tls:
  - hosts:
    - nginx.self.home
    secretName: nginx-tls-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirecttohttps
  namespace: nginx
spec:
  redirectScheme:
    permanent: false
    scheme: https