# nginx ca cert self signed 

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: cert-manager
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGL1RDQ0ErV2dBd0lCQWdJVUVOeWpkT1VMM3lXQWVMRGVEN1lwVGY2Q3U3d3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3Z1kweEN6QUpCZ05WQkFZVEFrbEVNUkF3RGdZRFZRUUlEQWRxWVd0aGNuUmhNUkF3RGdZRFZRUUhEQWRxDQpZV3RoY25SaE1ROHdEUVlEVlFRS0RBWjBaV3hyYjIweEREQUtCZ05WQkFzTUEzUnBhekVSTUE4R0ExVUVBd3dJDQpZV2QxYm1ka2MxMHhLREFtQmdrcWhraUc5dzBCQ1FFV0dXRm5kVzVuYzJGd2RYUnlielE0TkVCbmJXRnBiQzVqDQpieXd3SGhjTk1qSXdOekU0TURJME16UTVXaGNOTWpNd056RTRNREkwTXpRNVdqQ0JqVEVMTUFrR0ExVUVCaE1DDQpTVVF4RURBT0JnTlZCQWdNQjJwaGEyRnlkR0V4RURBT0JnTlZCQWNNQjJwaGEyRnlkR0V4RHpBTkJnTlZCQW9NDQpCblJsYkd0dmJURU1NQW9HQTFVRUN3d0RkR2xyTVJFd0R3WURWUVFEREFoaFozVnVaMlJ6WFRFb01DWUdDU3FHDQpTSWIzRFFFSkFSWVpZV2QxYm1kellYQjFkSEp2TkRnMFFHZHRZV2xzTG1OdkxEQ0NBaUl3RFFZSktvWklodmNODQpBUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTEVLVjN4SEdMeDlBdXBTSFUraE4wRVBDTTFraElDS3V3amgrN2lPDQpRZVlZRjhHM1lDV3NBam9SZ2VnVG5oL24vMW0rZXA4Rk16RG1KUWJQajdBY1RMdEhxYXN0ajUwRFBTM0lvUmFDDQpTWlc1RUVEMTkrckwxZmdjaGcycEc1SFVGZ3IvUEE0MzhCd0NMbU1nNHgvUXFQU3ZtY2tJMWhiK3AxTU40SkJiDQovUHlIYXcyTE11Y3l6b3c5QTU3TXZIT3FiQXJ3d1luc3FVcks0cG1EQm5yTnViak9mUmM5NURFZFdUWkJEME1wDQpzeWtLTGVwZVRoVHJtTHRISHpRWTR4V1JML1RIbk0wMzB3eXZoZkFGTUZaMXlBR1Z1STlUb3QwS2o1WnpFbzhEDQoyc2hKU2lOcEdWbVI5RlZRY2pzcFhjZ2ZVY2JnSk8wTXRHSW5jWC9rbS9vSEVZbkRmRFZHMDRqaXJRN3lOcDRnDQpUaGYzQ2ZOVGdDb1ZaQ2MyN2RDdFFvUlB0LzNXc1U5MzViM0hjQ3JvdjZiaFBZVnlLaHJsZ2lPTjEvcjhnOWJyDQpES3o4WThWMUU5cXA5d3djV1VFQ0dkaXdKYU9MaTluSUhXdzRoTmsrbTVyKzhEZ0loY0tEaWpWdnhnVkl3N0gwDQpVK0RJZk9lejFJb25FQkR2ckp4Q3NTUGU0UDBhZEE1WFUraXA1ZWpBcVlvcDZYNGRDRGppdGxmQndKQzRVWVJBDQoyR2Znek1kQlQrdTh3QzBPQVNrdERFL3E5Y3hCVXZvV3RNYzRMZ0gvR2RJZHpCTUd2cnBMb3U3WlhCTjE5ZDVjDQpWazl6cXZiU2F4ekVLQ044VTc0c3N2ZzNkSThoNHp6UXk5d2RXOVpKcVhJNHdoMEZORW9nQVcrRTd5YlJ6dUpQDQpDOFZOQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJTWElMZ1VKcTZ6azhFVUFIUXRTUC9DbjQ5am9UQWZCZ05WDQpIU01FR0RBV2dCU1hJTGdVSnE2ems4RVVBSFF0U1AvQ240OWpvVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHDQpDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVgwOGxZYk1Jb3hkSDNGaWtzV3lpamd2V1lseHpoYkVpcE5Vc0x1Z05uDQpqWjVHOVg2Zm9FRFFNSkV4aTk3VTluQ1BMN3EvUXdBdVdKNkMzY3B6eVc0Wi83OEtNVEE1VjdpVkpXaHBHRDBHDQo1dm0vamdiL0EyVEY1a1ZlUi9rbjJxU0F2Sjhab3dLclhxbXhuZkEzSUhHeDliVnJuZDJoZFkyOWE3Um5BNmhaDQpUMnpuKzJsaEdwUVA0S2I4eFlhQlVYK2lENThvemc4SmlKc1ZnR2JTVzI4MUU1OXN1TXRGbXl1V1I5a2VWbnhoDQpTQldSelFnRHBMT1A3WUZSN2tQVFg1TGpJMnprVzZXaVdFK3VNaExOQ0h2aDZHbzlwbng3VEw0VkkrQXc2UTduDQpGMHNNQkppZk9XMllqRzRDTC83TmNnYzh6S3JaUTBKRUgxbHlQcTNWUEZ2VU8wbTRXRW1WbWVlMit4Z2hCdVp6DQprVUtpVC8ramxiUHQvWXBJWjROOUZ3dUdwT09vVys1OEJ0QXJLMW5XaUtKamU2KytMMk80RzRSNU1rUzV6TDFSDQpLTjFsSVVOaDNyOVlsRk1raUwxTkljazBkcGI1bmc3L0pPdngrUCtudVpVM1ZrdXFLUk1lUFlFQVlJUkhNNHBTDQpSOHpTTmlNQmJnZlo1YmZZWk9oaVFJMkVsQ2tuS1BVY1JzdG5VNDdiVzJISXcwRWkxUlRTQUFYSzk3S2F4NXY0DQpDVkhpb09JQkRLNmFPdzE2NlhCUDY1RWR4NytWTHg3N3ZDZlNHSk5IcU5HSGIvM3JXVWdWOGtJSlEyRkVEQmFQDQpXb01rMVY1RXY1NjgyMkpsR2pJbDBZRHF1NzcydkJvZHVTUDlwVHovaUlHVlZiQzZONU1MamhFb3lpRmVXZThRDQpqQT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo= # content of ca.crt (converted to base64)
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJSktnSUJBQUtDQWdFQXNRcFhmRWNZdkgwQzZsSWRUNkUzUVE4SXpXU0VnSXE3Q09IN3VJNUI1aGdYd2JkZw0KSmF3Q09oR0I2Qk9lSCtmL1diNTZud1V6TU9ZbEJzK1BzQnhNdTBlcHF5MlBuUU05TGNpaEZvSkpsYmtRUVBYMw0KNnN2VitCeUdEYWtia2RRV0N2ODhEamZ3SEFJdVl5RGpIOUNvOUsrWnlRaldGdjZuVXczZ2tGdjgvSWRyRFlzeQ0KNXpMT2pEMERuc3k4YzZwc0N2REJpZXlwU3NyaW1ZTUdlczI1dU01OUZ6M2tNUjFaTmtFUFF5bXpLUW90Nmw1Tw0KRk91WXUwY2ZOQmpqRlpFdjlNZWN6VGZUREsrRjhBVXdWblhJQVpXNGoxT2kzUXFQbG5NU2p3UGF5RWxLSTJrWg0KV1pIMFZWQnlPeWxkeUI5Unh1QWs3UXkwWWlkeGYrU2IrZ2NSaWNOOE5VYlRpT0t0RHZJMm5pQk9GL2NKODFPQQ0KS2hWa0p6YnQwSzFDaEUrMy9kYXhUM2ZsdmNkd0t1aS9wdUU5aFhJcUd1V0NJNDNYK3Z5RDF1c01yUHhqeFhVVA0KMnFuM0RCeFpRUUlaMkxBbG80dUwyY2dkYkRpRTJUNmJtdjd3T0FpRndvT0tOVy9HQlVqRHNmUlQ0TWg4NTdQVQ0KaWljUUVPK3NuRUt4STk3Zy9ScDBEbGRUNktubDZNQ3BpaW5wZmgwSU9PSzJWOEhBa0xoUmhFRFlaK0RNeDBGUA0KNjd6QUxRNEJLUzBNVCtyMXpFRlMraGEweHpndUFmOFowaDNNRXdhK3VrdWk3dGxjRTNYMTNseFdUM09xOXRKcg0KSE1Rb0kzeFR2aXl5K0RkMGp5SGpQTkRMM0IxYjFrbXBjampDSFFVMFNpQUJiNFR2SnRITzRrOEx4VTBDQXdFQQ0KQVFLQ0FnQTRhbWMrZnhsdTF4ZGF2QmdEREFpamZycjdXSkN3dFlTc2EvYmU5TllqRUlKaGhLSHEzMGxHWDlYWg0Kc29hcy9DenUyRGdTL0lFM2o5ODBzR2ZGWXY5QW5yRitqdUk0MHBOb1I0cXR0WTdsV3pmR3U1cnBBMU9INE84Rw0KNDJDWnM4L2lhVHNsL01WUzU0OEluNjVBc1NsbDc1ODk1TWIwUk9ubEdZTDUvWlk4a3BxV2tra0NTN3B1RGZOZA0KWXppYVV6Qml2QjJ3YWUzNG0zWmlITkt2eDJicmNVR0Rhb0dROVIwOG9MYlFYRFZ2V29NUE1FWUpmSm9LODdzSg0KeXZSeUp2WDFOcmJNM29FdWhiQlVzQktiT3FVbGZDUjM1OXI2UFNkTWRoYnY0L2FQNUdydnBjb2lOTlI3YTBzNw0KZHc4ZmVudUF1R1NMOVlSMTBzUGtVV0V5NTVXNm5OMzhOWXhuZm5FYWxCSDB5UHFDbTBObE11Q3NjQ3laUTBHVA0KV1EwVVU3MGxZRFYzQm5Sc0hhMG5BQ3BueXVCMWhKQjF3aFVmVHVIVVJWamt1TEc5aVhReURRaENxTDN0T2FOZw0KSEJuK09oZ0V6L3p6b0lPbzVlT0FYWmFoV21XSnZOVnMzNStPYXg3UTZ2SVgrNUVQS1A1dHI4d0lUcmczaEpnUA0KNk55SnVqaEtrb2JzVmhjdEVxdGd3VzhFK1JyTnNUbEdGRFRMTGp6aHJSR2R5bFF0L1NsVnd1V3c4d1p4b2h6UA0KdFE5bzZPaFFDWFVSNlRDUDRlT0ZvNXNIZENVN3Zzc3BwQ2RSNFlTVXZGdHFHanVMZ2w5N05tNjlGY2NFSXJpcQ0KKzVTczJyVjZKRGNPamt5c2M2UUM4UE9FdG0rb3ZvV0xadm0xNy9JejlpbW5uT0tGZ1FLQ0FRRUE0VnpndzF3Zg0KRDR4Q3pRY0FCaVJTSkJpR1JUcmx0enZwZzY2WXNodTAxUk9DSDBZbDA3MWdPc2IxaUtyVUJZODl5VTVWaGo4Mg0Kbkg0VXB4dGRyL2VVWUpKZFpIdnY5cjdQeWluV3ZCbFB6dmIrNGMvcitQRGdzbFlFbGkzZWN4U3Q0SWVXMHBFVQ0KNU5oOXphaWlENlE0LzhIMlE5c01NM1VNbHNsY3VRamZsWUJVNE54anNocWhHVDNHVzRSS3krVm1kbXA2L29BMA0KWDR1WVVVU3cyTFBlZ3d0bS9XekFaREJueVltWkwxZkFGOFJPRXppR2hJUmhMcC82NytDNi9Tby80YWxqNTN6Ug0KeURRb1p1Z2pSOWxIOStNUklSdjZkcXltNXZMS2hwamFLOUtIdjBkMmd2NDFwNzV3MDM2eTlSTS9ja0JHamNucg0KTnRZZGJsYlB3eEplbVFLQ0FRRUF5UnU4ejlvYWdQMnRiN1dRaUg3WmcyKzZqSFU2dnpxMWNLQXNiUmsySk1TaQ0KbFRVOGEva1ErODE4QSs1N0JsWVFybXlKUnB5VzQrYjZNN1ZVNE1odU9zOWFheTE0Y1FTdGw0OG5tR1oraUZzNg0KTm54S0JadnVIQ3RTWFZLaVpqYkp1UDR5NHVJYkVUYWk5M2NDK2pMaDlmZlBGbEpXaTJlTjM4Z3RDb0tIWVBBRQ0KNlU2NFE1c0RGN3lKL2NtRzJ3RFNhcEJRdWZXRlE4NUwrcjdVSkptNGtYNURibHRBbmd4blhPZUg3VDI3Tnc3ZA0KTzU5dm51aENIWVMzbG91VE1NRm5PVE05K3pUK20zOEZrdk1zaFltb2lGaDVzdlBLdVUzYzNNOUJLcVJKVE1UVQ0KNk9UKzN2K3R6M3gydFpYUWMyKzRyTGRpeVZEbmszbzRnU20rMFJXUTFRS0NBUUVBaUJuS1Y5RmJwTTBsVHFNSw0KbmFyenZIN2ZJQkk0eHhjMHFHVWFMSDVWRUZXdXdPcGhUK1hQcHMrZlcwRW51SS9RVmJHc0x0NGdRaFJXcnJEMQ0KUEo4OWliRDdIQU5KWVcvTkY1OTY0ckE2cFpnL1IrcUU3UnV6NTUvUk4wMU9TWnZVZ29RQVR2eDFiTnRkNW9VUQ0KRW5nd1FDMUlaNlJ6VXVRK2pSWGduSkxDVEl4ck5qMkRLLzJ2Q3dwbXI4Qk9WNk1iNVNuYlM3WHJhMFJuNGJTbA0KUk1vaitHbzdjWk5yQVZiR1owMWxLTlZLMmsrZ2d6VWc4QWp1ay9UajNGaVJOUEYrRU85MnVVZUZmZTRaOUVQLw0KZ3BXelEvNXF5dDhWdlBQNS9BSG0wN0NlR2RjVVNpMkRZZ3JhSm9yNW9wQ2l6U1VwclBzcVlOanY1M2NaNFJnbQ0KY3YyMkNRS0NBUUVBaVpUclIvczY5SklYcS91M3BGbTdydHFwOGR0bFZGdnlzdGt4YTNXNi84NXlOOGVTelg4NA0KS2p1Nm91bnN5am5vOFpzWkV2Q2ZuY3h2MFI0MXNnNE1zemtWNzRyTkFleWtZYkl5OFdUMUhZM2p0bEN6UjBFVQ0KMWJxaGYyeS80MU9LRDRBQUNnMkxYT3hXOHhzOU16UEtPRDdQTXNNanAvMHhKeTVIK2crd1ZCWUFGaWlma01paw0KaGdHYkdiOWIvY21ES2hvTzBCbHlrUis2QlJHMkNsQUwzNlZVdGxQQlVoN0VPOSs5c3dUdlpreEo5N2NzWXJjYw0KUEJ1R2lYeDFOdjZwQW8zVzBsdS83MXNuMGcrQW50NjlLSUgyeUFGVzZBeW5rM3hLWmNTOHpNTS9zUkN3ZUpqTQ0KTE0xR1hSWGY1SWxDK3czK2pDRklQREY2SklzTm12YTQvUUtDQVFFQW03MG4wN0lYT1R2MUE2dnUrMjAxK1gwag0KSGtiTDY1MTZTVFZsVzlWNlRYcmtTNkpaeTZZOUtrckQwY1d6VFpjeEpZdGJuZkd0TlY1UUM5RmxVTlhmNVdxVw0KTE1Kbk91ZVhYb2N4a0VHUnMyd1VDRW9BVmMvenJrUEVadUZ1WC82OTQzamVqOXpMNjJObmh0N1RXcXMvWmx0Rg0KeW9KM1oxZlllU1VuMnN3cG5OOTV3TnlTRWRKSkY1U0daaGRwWlRWZEQwUGk4cVVUeDMwQ1BSM2lxajhkaURxLw0KWktKeDlGNkd6anROcjF3eXR3cUc0blVwUEFzK2R6aWFtVGhSZnRRcDhteWowVTlreExXbmsreEllVEorUWdDRA0KeEt4L21KaG12WnNqa0ptSFpQY3pjWURMcEdPdVV4THhTb3o1RTBqelNGUi9lblpEdXhsRVh5ZFRxVUVjanc9PQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg== # content of ca.key (converted to base64)
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nginx-clusterissuer
spec:
  ca:
    secretName: nginx-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: nginx
spec:
  secretName: nginx-tls-secret
  issuerRef:
    name: nginx-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.self.home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
  labels:
    app: nginx-app
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: nginx-redirecttohttps@kubernetescrd
spec:
  rules:
  - host: "nginx.self.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc 
            port:
              number: 80 
  tls:
  - hosts:
    - nginx.self.home
    secretName: nginx-tls-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirecttohttps
  namespace: nginx
spec:
  redirectScheme:
    permanent: false
    scheme: https