name: CI/CD Github action
description: github action 
on: 
  push:
    branches:
      - 'master'
jobs:
  build:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
      - name: checkout
        uses: actions/checkout@v2 # first action : checkout source code
    
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image # push The image to the docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapp:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simpleapp:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simpleapp:buildcache,mode=max