image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: "Build and Test"
        services:
          - docker
        script:
          - IMAGE="bitbucketpipelines/hello-app"
          - VERSION="${BITBUCKET_BUILD_NUMBER}"
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          - docker build -t ${IMAGE} .
          - docker tag ${IMAGE} ${IMAGE}:${VERSION}
          - docker push ${IMAGE}
    - step:
        name: "Deploy to PROD"
        deployment: production
        script:
          - envsubst < helloweb-deployment.tpl.yaml > helloweb-deployment.yaml
          - pipe: atlassian/google-gke-kubectl-run:0.1.1
            variables:
              KEY_FILE: ${KEY_FILE}
              PROJECT: pipes-alexk-serverless-deploy
              COMPUTE_ZONE: us-east1
              CLUSTER_NAME: "hello-cluster"
              KUBECTL_COMMAND: apply
              SPEC_FILE: helloweb-deployment.yaml
              KUBECTL_ARGS:
                - "--dry-run"
